INSERT INTO
    EmployeeBasicInfo (
        employee_id,
        employee_name,
        gender,
        date_of_birth,
        position,
        region,
        date_of_hire
    )
VALUES
    (
        'E001',
        '王小花',
        '女',
        '1990-01-01',
        '總經理',
        '全區',
        '2023-01-01'
    ),
    (
        'E002',
        '王大文',
        '男',
        '1985-05-15',
        '廠長',
        '北區',
        '2024-01-02'
    ),
    (
        'E002',
        '林中人',
        '男',
        '1988-05-15',
        '廠長',
        '中區',
        '2022-01-23'
    );