server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    error_page 404 /index.html;

    location /api/ {
        proxy_pass http://backend:5000;
    }
}
