upstream backend {
    server ${BACKEND_HOST}:3000;
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    error_page 404 /index.html;

    location /api/ {
        proxy_pass http://${BACKEND_HOST}:3000;
    }
}
