INSERT INTO
    CompanyInfo (
        unified_number,
        business_assignee,
        company_name,
        contact_person,
        mobile_phone,
        department,
        contact_phone,
        fax_number,
        contact_email,
        company_address,
        delivery_address,
        note,
        registration
    )
VALUES
    (
        '12345678',
        '李世民',
        'Tech Solutions Ltd.',
        'John Doe',
        '0912345678',
        'Engineering',
        '02-12345678',
        '02-87654321',
        'contact@techsolutions.com',
        'No.1, Taipei Road, Taipei',
        'No.1, Taipei Road, Taipei',
        'Trusted partner',
        TRUE
    ),
    (
        '87654321',
        '陳列',
        'Green Energy Corp.',
        'Jane Smith',
        '0987654321',
        'R&D',
        '07-12345678',
        '07-87654321',
        'info@greenenergy.com',
        'No.99, Kaohsiung Blvd, Kaohsiung',
        'No.99, Kaohsiung Blvd, Kaohsiung',
        'Reliable service',
        FALSE
    );INSERT INTO
    CostEntry (
        inquiry_number,
        production_type,
        material,
        product_dimensions,
        exchange_rate,
        tariff,
        shipping_cost,
        material_cost,
        blade_cost,
        blade_cost_notes,
        mold_cost,
        mold_cost_notes,
        other_cost,
        other_cost_notes,
        total_cost,
        total_processing_time,
        processing_cost,
        outsourcing_company,
        outsourcing_cost,
        processing_and_outsourcing_total,
        total_final_cost,
        content_notes,
        factory_signature,
        factory_deputy_signature,
        manager_signature,
        manager_approval_signature,
        lathe,
        milling_machine,
        cnc,
        `manual`,
        saw,
        backup_field1,
        backup_field2,
        backup_field3,
        created_at,
        updated_at
    )
VALUES
    (
        1001,
        'Manufacturing',
        'Steel',
        '10x20x30',
        1.2,
        10.00,
        50.00,
        500.00,
        100.00,
        'Blade sharpening',
        200.00,
        'Custom mold',
        30.00,
        'Miscellaneous',
        890.00,
        12.5,
        100.00,
        'Outsource Co.',
        150.00,
        250.00,
        1140.00,
        'Urgent order',
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        '2025-01-01',
        '2025-01-01'
    ),
    (
        1002,
        'Assembly',
        'Aluminum',
        '15x25x35',
        1.3,
        15.00,
        40.00,
        300.00,
        120.00,
        'Blade replacement',
        250.00,
        'New mold design',
        20.00,
        'Additives',
        745.00,
        10.0,
        80.00,
        'Fabricators Inc.',
        100.00,
        180.00,
        925.00,
        'Standard order',
        FALSE,
        FALSE,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        '2025-01-02',
        '2025-01-02'
    );INSERT INTO
    MaterialInfo (material_name, material_cost, unit_name)
VALUES
    ('鐵', 50.00, 'kg'),
    ('鉛', 70.00, 'kg'),
    ('銅', 80.00, 'kg'),
    ('塑膠', 20.00, 'kg');INSERT INTO
    EmployeeBasicInfo (
        employee_id,
        employee_name,
        gender,
        date_of_birth,
        position,
        region,
        date_of_hire
    )
VALUES
    (
        'E001',
        '王小花',
        '女',
        '1990-01-01',
        '總經理',
        '全區',
        '2023-01-01'
    ),
    (
        'E002',
        '王大文',
        '男',
        '1985-05-15',
        '廠長',
        '北區',
        '2024-01-02'
    ),
    (
        'E002',
        '林中人',
        '男',
        '1988-05-15',
        '廠長',
        '中區',
        '2022-01-23'
    );INSERT INTO
    OutsourcingVendor (
        company_name,
        unified_number,
        contact_window,
        contact_phone,
        fax_number,
        contact_email,
        mobile_phone,
        company_address,
        transaction_details,
        note,
        registration
    )
VALUES
    (
        'Outsource Co.',
        '11223344',
        'Tom Hanks',
        '03-1234567',
        '03-7654321',
        'support@outsource.com',
        '0911223344',
        'No.123, Outsource St., Taoyuan',
        'CNC machining services',
        'High quality',
        TRUE
    ),
    (
        'Fabricators Inc.',
        '55667788',
        'Emma Watson',
        '05-7654321',
        '05-1234567',
        'contact@fabricators.com',
        '0988112233',
        'No.456, Fabrication Rd., Tainan',
        'Welding and assembly',
        'On-time delivery',
        FALSE
    );